### Obtener todos los usuarios
GET http://localhost:8080/api/v1/users/

### Obtener usuarios cuyo nombre contiene 'eo'
GET http://localhost:8080/api/v1/users/name?q=eo

### Obtener publicaciones por id
GET http://localhost:8080/api/v1/publications/1

### Obtener todas las publicaciones
GET http://localhost:8080/api/v1/publications/

### Registrar un nuevo usuario
POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"username": "Rodrygo Goeeeeees",
	"email": "abcd@gmail.com",
	"password": "Abcd",
	"rol": "USER"
}

### Logearse
POST http://localhost:8080/auth/login
Content-Type: application/json

{
	"username": "Rodrygo Goeeeeees",
	"password": "Abcd"
}

### Actualizar el username del usuario autenticado
PATCH http://localhost:8080/api/v1/users/me/newName?newName=Paquito
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJvZHJ5Z28gR29lZWVlZWVzIiwidXNlcklkIjozLCJzdWIiOiJSb2RyeWdvIEdvZWVlZWVlcyIsImlhdCI6MTc2MTU4NjczNCwiZXhwIjoxNzYxNTg4MTc0fQ.6_PNUR2w3bIqBF3E-BJr9PwuM-1l7upMPrEuplxLUfc


### Obtener todos los usuarios que sigue un usuario
GET http://localhost:8080/api/v1/follows/eordunap/following

### Obtener todos los usuarios que siguen a un usuario
GET http://localhost:8080/api/v1/follows/NuevoNombre/followers







### Editar la nacionalidad del jugador por id
PATCH http://localhost:8080/api/v1/players/change_nationality/31
Content-Type: application/json

{
	"countryName": "Spain"
}

### Borrar jugador por id
DELETE http://localhost:8080/api/v1/players/35

### Insertar pais
POST http://localhost:8080/api/v1/countries/
Content-Type: application/json

{
	"countryName": "Trabubulandia"
}
