### Obtener todos los usuarios
GET http://localhost:8080/api/v1/users/

### Obtener usuarios cuyo nombre contiene 'eo'
GET http://localhost:8080/api/v1/users/name?q=eo

### Obtener publicaciones por id
GET http://localhost:8080/api/v1/publications/1

### Registrar un nuevo usuario
POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"username": "Rodrygo Goeeeeees",
	"email": "ED",
	"password": "Abcd",
	"rol": "USER"
}

### Logearse
POST http://localhost:8080/auth/login
Content-Type: application/json

{
	"username": "Rodrygo Goeeeeees",
	"password": "Abcd"
}

### Actualizar el username del usuario autenticado
PATCH http://localhost:8080/api/v1/users/me/newName?newName=NuevoNombre
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiUm9kcnlnbyBHb2VlZWVlZXMiLCJzdWIiOiJSb2RyeWdvIEdvZWVlZWVlcyIsImlhdCI6MTc2MTU2MDY2MywiZXhwIjoxNzYxNTYyMTAzfQ.a3ajyfxGv4csq_lnCdEkAdqdKPm5tLubIv5duuuQXSQ


### Insertar un nuevo jugador
POST http://localhost:8080/api/v1/players/
Content-Type: application/json

{
	"playerName": "Rodrygo Goeeeeees",
	"playerPosition": "ED",
	"playerBirthDate": "2001-01-09",
	"playerTeam": "Real Madrid",
	"countryName": "Brazil"
}

### Editar la nacionalidad del jugador por id
PATCH http://localhost:8080/api/v1/players/change_nationality/31
Content-Type: application/json

{
	"countryName": "Spain"
}

### Borrar jugador por id
DELETE http://localhost:8080/api/v1/players/35

### Insertar pais
POST http://localhost:8080/api/v1/countries/
Content-Type: application/json

{
	"countryName": "Trabubulandia"
}
